### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "jj@gmail.com",
    "password": "hello"
}


####
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "dd@gmail.com",
    "password": "hello"
}

####
GET http://localhost:3000/auth/profile
Content-Type: application/json

###
POST http://localhost:3000/auth/signout
Content-Type: application/json


### Not create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "kdjfnfksnjkfnkdsnfjkdsil.com",
    "password": "dfjnskfdksnjfds",
    "jhbdsjh": "dfjnskfdksnjfds"
}


### Get a user
GET http://localhost:3000/auth/2
Content-Type: application/json


### Get a user by email
GET http://localhost:3000/auth?email=asdf@gmail.com
Content-Type: application/json


### Remove a user
DELETE  http://localhost:3000/auth/1
Content-Type: application/json


### Update user
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "jjjjjj@gmail.com"
}
